#!groovy
import hudson.*;

node {
    // Get all Causes for the current build
    def causes = currentBuild.getBuildCauses()

    // Get a specific Cause type (in this case the user who kicked off the build),
    // if present.
    def specificCause = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')

    // First we'll generate a text file in a subdirectory on one node and stash it.
    stage "first step on first node"

    
    stage('first-node') {
        print 'first stage test'
        print 'causes ${causes}'
        sh "ls -la"
        print 'first stage test finished'
    }

    stage "second step on second node"

    stage('second-node') {
        print 'second stage test'
        try{
        sh "mkdir build"
        } catch (Exception e) {
                echo 'Exception occurred: ' + e.toString()
                sh 'echo Handle the exception!'
        }
        sh "cd build"
        sh "pwd"
        try {
            sh "rm -rf jpasamplehsqldb"
        } catch (Exception e) {
                echo 'Exception occurred: ' + e.toString()
        }    
        sh "git clone https://github.com/sureshbenedy/jpasamplehsqldb.git"
        sh "cd jpasamplehsqldb ; pwd ; mvn clean install"
        print 'specificCause ${specificCause}'
        print 'second stage test finished'
    }
}
