#!groovy

node {
    // Get all Causes for the current build
    def causes = currentBuild.getBuildCauses()

    // Get a specific Cause type (in this case the user who kicked off the build),
    // if present.
    def specificCause = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')

    // First we'll generate a text file in a subdirectory on one node and stash it.
    stage "first step on first node"

    
    stage('first-node') {
        print 'first stage test'
        print 'causes ${causes}'
        print 'first stage test finished'
    }

    stage "second step on second node"

    stage('second-node') {
        print 'second stage test'
        print 'specificCause ${specificCause}'
        print 'second stage test finished'
    }
}
